version: '3.7'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5442:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres_service/postgresql:/var/lib/postgresql
      - ./postgres_service/setup:/docker-entrypoint-initdb.d
  node:
    build: ./node_service
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
  # pentaho:
  #   build: ./pentaho_service
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - ./pentaho_service/data/pentaho-hsqldb-data:/opt/pentaho/pentaho-server/data/hsqldb:rw
  #     - ./pentaho_service/data/pentaho-jackrabbit-data:/opt/pentaho/pentaho-server/pentaho-solutions/system/jackrabbit/repository:rw
  #     - ./pentaho_service/logs:/opt/pentaho/pentaho-server/tomcat/logs
  #   environment:
  #     TZ: America/Sao_Paulo