version: '3.7'
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5442:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./postgres_service/postgresql:/var/lib/postgresql
      - ./postgres_service/setup:/docker-entrypoint-initdb.d
  node:
    build: ./node_service
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
